/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIPrincipal.java
 *
 * Created on 22/08/2011, 15:41:31
 */
package tcc.uniban.parkinglot.visao.gui;

import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import tcc.uniban.parkinglot.visao.ouvinte.OuvinteDeGUICadastroDeFuncionario;
import tcc.uniban.parkinglot.visao.ouvinte.OuvinteDeGUIFuncionarios;

/**
 *
 * @author eduardo
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private GUIFuncionario guiFuncionario;

    /** Creates new form GUIPrincipal */
    public GUIPrincipal() {
        initComponents();
        lookandfeel();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemDeMenuImportar = new javax.swing.JMenuItem();
        itemDeMenuExportar = new javax.swing.JMenuItem();
        itemDeMenuSair = new javax.swing.JMenuItem();
        itemDeMenuEntradaESaida = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        itemDeMenuVeiculos = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        itemDeMenuLoja = new javax.swing.JMenuItem();
        itemDeMenuMenslista = new javax.swing.JMenuItem();
        itemDeMenuTarifas = new javax.swing.JMenuItem();
        itemDeMenuFuncionario = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        itemDeMenuDiario = new javax.swing.JMenuItem();
        itemDeMenuPeriodo = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemDeMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ParkingLot");

        desktopPane.setBackground(new java.awt.Color(236, 233, 216));
        desktopPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        desktopPane.setDesktopManager(null);

        menuArquivo.setMnemonic('f');
        menuArquivo.setText("Arquivo");

        itemDeMenuImportar.setMnemonic('o');
        itemDeMenuImportar.setText("Importar...");
        menuArquivo.add(itemDeMenuImportar);

        itemDeMenuExportar.setMnemonic('s');
        itemDeMenuExportar.setText("Exportar...");
        menuArquivo.add(itemDeMenuExportar);

        itemDeMenuSair.setMnemonic('x');
        itemDeMenuSair.setText("Sair");
        itemDeMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemDeMenuSair);

        menuBar.add(menuArquivo);

        itemDeMenuEntradaESaida.setMnemonic('e');
        itemDeMenuEntradaESaida.setText("Operação");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Entrada/Saida Veiculos");
        itemDeMenuEntradaESaida.add(cutMenuItem);

        menuBar.add(itemDeMenuEntradaESaida);

        itemDeMenuVeiculos.setText("Cadastro");

        jMenuItem3.setText("Veiculos");
        itemDeMenuVeiculos.add(jMenuItem3);

        itemDeMenuLoja.setText("Loja");
        itemDeMenuVeiculos.add(itemDeMenuLoja);

        itemDeMenuMenslista.setText("Mensalista");
        itemDeMenuVeiculos.add(itemDeMenuMenslista);

        itemDeMenuTarifas.setText("Tarifas");
        itemDeMenuVeiculos.add(itemDeMenuTarifas);

        itemDeMenuFuncionario.setText("Funcionários");
        itemDeMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuFuncionarioActionPerformed(evt);
            }
        });
        itemDeMenuVeiculos.add(itemDeMenuFuncionario);

        menuBar.add(itemDeMenuVeiculos);

        menuRelatorios.setText("Relatórios");

        itemDeMenuDiario.setText("Diário");
        menuRelatorios.add(itemDeMenuDiario);

        itemDeMenuPeriodo.setText("Período");
        menuRelatorios.add(itemDeMenuPeriodo);

        menuBar.add(menuRelatorios);

        menuAjuda.setMnemonic('h');
        menuAjuda.setText("Ajuda");

        itemDeMenuSobre.setMnemonic('a');
        itemDeMenuSobre.setText("Sobre");
        itemDeMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemDeMenuSobre);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDeMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemDeMenuSairActionPerformed

private void itemDeMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSobreActionPerformed
    if ((guiSobre == null) || (!guiSobre.isVisible())) {
        guiSobre = new GUISobre();
        desktopPane.add(guiSobre);
        guiSobre.setPosicao();
        guiSobre.setVisible(true);
    }
}//GEN-LAST:event_itemDeMenuSobreActionPerformed

private void itemDeMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuFuncionarioActionPerformed
    if ((guiFuncionario == null) || (!guiFuncionario.isVisible())){
        guiFuncionario = new GUIFuncionario();
        OuvinteDeGUIFuncionarios ouvinte = new OuvinteDeGUIFuncionarios(guiFuncionario);
        desktopPane.add(guiFuncionario);
        guiFuncionario.setPosicao();
        guiFuncionario.setVisible(true);
    }
    try {
        guiFuncionario.setSelected(true);
    } catch (PropertyVetoException exc){
            StringBuffer mensagem = new StringBuffer();
            mensagem.append("Não foi possível selecionar a janela de cadastro!");
            mensagem.append("\nMotivo: " + exc.getMessage());
            GUIMensagem.exibirMensagem(mensagem.toString(), "ParkingLot - Cadastro de funcionário", true);
    }
}//GEN-LAST:event_itemDeMenuFuncionarioActionPerformed

public void lookandfeel(){
    try {  
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
        SwingUtilities.updateComponentTreeUI(this);
    } catch (Exception e) {  
           e.printStackTrace();  
    }  
}




    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemDeMenuDiario;
    private javax.swing.JMenu itemDeMenuEntradaESaida;
    private javax.swing.JMenuItem itemDeMenuExportar;
    private javax.swing.JMenuItem itemDeMenuFuncionario;
    private javax.swing.JMenuItem itemDeMenuImportar;
    private javax.swing.JMenuItem itemDeMenuLoja;
    private javax.swing.JMenuItem itemDeMenuMenslista;
    private javax.swing.JMenuItem itemDeMenuPeriodo;
    private javax.swing.JMenuItem itemDeMenuSair;
    private javax.swing.JMenuItem itemDeMenuSobre;
    private javax.swing.JMenuItem itemDeMenuTarifas;
    private javax.swing.JMenu itemDeMenuVeiculos;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuRelatorios;
    // End of variables declaration//GEN-END:variables
    private GUISobre guiSobre;

}
